QT.core_private.VERSION = 6.8.3
QT.core_private.name = QtCore
QT.core_private.module =
QT.core_private.libs = $$QT_MODULE_LIB_BASE
QT.core_private.includes = $$QT_MODULE_INCLUDE_BASE/QtCore/6.8.3 $$QT_MODULE_INCLUDE_BASE/QtCore/6.8.3/QtCore
QT.core_private.frameworks = 
QT.core_private.depends = core
QT.core_private.uses = 
QT.core_private.module_config = v2 internal_module
QT.core_private.enabled_features = doubleconversion broken-threadlocal-dtors mimetype-database cpp-winrt sha3-fast hijricalendar datetimeparser pcre2 debug x86intrin sse2 sse3 ssse3 sse4_1 sse4_2 avx f16c avx2 avx512f avx512er avx512cd avx512pf avx512dq avx512bw avx512vl avx512ifma avx512vbmi avx512vbmi2 aesni vaes rdrnd rdseed shani localtime_s alloca_malloc_h alloca dbus gui network printsupport sql testlib widgets xml openssl relocatable intelcet msvc_obj_debug_info force_debug_info largefile precompile_header sse2 sse3 ssse3 sse4_1 sse4_2 avx f16c avx2 avx512f avx512er avx512cd avx512pf avx512dq avx512bw avx512vl avx512ifma avx512vbmi avx512vbmi2 aesni vaes rdrnd rdseed shani
QT.core_private.disabled_features = clock-gettime system-doubleconversion dladdr futimens getauxval getentropy glib icu inotify journald system-libb2 linkat memmem memrchr system-pcre2 poll_ppoll poll_pollts poll_poll poll_select posix_sem posix_shm qqnx_pps renameat2 slog2 syslog sysv_sem sysv_shm backtrace cxx23_stacktrace timezone_locale lttng etw ctf forkfd_pidfd poll-exit-on-error openssl-hash use_bfd_linker use_gold_linker use_lld_linker use_mold_linker android-style-assets gc_binaries developer-build private_tests elf_private_full_version reduce_exports no_direct_extern_access mips_dsp mips_dspr2 neon arm_crc32 arm_crypto localtime_r posix_fallocate alloca_h system-zlib stdlib-libcpp dbus-linked libudev dlopen glibc_fortify_source trivial_auto_var_init_pattern stack_protector stack_clash_protection libstdcpp_assertions libcpp_hardening relro_now_linker
QMAKE_LIBS_OPENSSL =
QMAKE_LIBS_OPENSSL_DEBUG = -L"C:/openssl/lib/VC" -llibssl64MDd -llibcrypto64MDd -lcrypt32 -lws2_32
QMAKE_LIBS_OPENSSL_RELEASE = -L"C:/openssl/lib/VC" -llibssl64MD -llibcrypto64MD -lcrypt32 -lws2_32
QMAKE_INCDIR_OPENSSL = C:/openssl/include
QMAKE_LIBS_LIBATOMIC = 
