/* This file was generated by syncqt. */
#ifndef QT_QTNETWORK_VERSION_H
#define QT_QTNETWORK_VERSION_H

#define QTNETWORK_VERSION_STR "6.8.3"

#define QTNETWORK_VERSION 0x060803

#endif // QT_QTNETWORK_VERSION_H
